### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by MerlinB** [tokenized/bitcoin_reader#1]
When running `main.go`, most of the time it fails after a few seconds with this: 

```
panic: runtime error: index out of range [0] with length 0

goroutine 168 [running]:
github.com/tokenized/bitcoin_reader.(*NodeManager).nextNode(0xc000261540, {0xb459d8, 0xc0003512c0}, 0x0)
        /home/merlin/Devel/bitcoin_reader/node_manager.go:222 +0xc85
github.com/tokenized/bitcoin_reader.(*NodeManager).RequestTxs(0xc000261540, {0xb459d8, 0xc00030f5c0})
        /home/merlin/Devel/bitcoin_reader/node_manager.go:161 +0x171
github.com/tokenized/pkg/threads.(*Thread).runPeriodic(0xc00056af00, {0xb459d8, 0xc00030f5c0})
        /home/merlin/Devel/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:216 +0xa5
github.com/tokenized/pkg/threads.(*Thread).Start.func1()
        /home/merlin/Devel/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:179 +0x150
created by github.com/tokenized/pkg/threads.(*Thread).Start
        /home/merlin/Devel/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:169 +0x17a
exit status 2
```

I worked a few times, I could not yet figure out a pattern.
The last message in the log is always `Finished: Node: [54.243.212.219]:8333: connect: dial tcp 54.243.212.219:8333: i/o timeout` (with a different IP). There are lots of "connection refused" errors in the log as well.

**Comment by MerlinB** [comment]
This happens when no connection with another node can be established. Not sure why all connections fail. For reference here is the full log: 

```
{"level":"info","ts":1656861243.309619,"caller":"node/main.go:87","msg":"Started : Application Initializing"}
{"level":"info","ts":1656861243.309701,"caller":"node/main.go:90","msg":"Build unknown (unknown on unknown)"}
{"level":"info","ts":1656861243.313129,"caller":"headers/branches.go:629","msg":"Loaded branch","branch":"000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f","block_height":0,"length":1}
{"level":"info","ts":1656861243.313366,"caller":"headers/headers.go:1190","msg":"No historical header hash heights to load"}
{"level":"info","ts":1656861243.313492,"caller":"headers/headers.go:1163","msg":"Loaded headers","block_height":0,"block_hash":"000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"}
{"level":"info","ts":1656861243.314114,"caller":"bitcoin_reader/peers.go:204","msg":"Loaded 42 peers"}
{"level":"info","ts":1656861243.314189,"caller":"node/main.go:124","msg":"User Agent : /Tokenized/Spynode:Test-unknown/"}
{"level":"verbose","ts":1656861243.315397,"caller":"bitcoin_reader/node_manager.go:813","msg":"Retrieved peers for score range 1 to 4","peer_count":0}
{"level":"verbose","ts":1656861243.315500,"caller":"bitcoin_reader/node_manager.go:835","msg":"Peers for score 1","peer_count":0}
{"level":"info","ts":1656861243.315691,"caller":"bitcoin_reader/node_manager.go:272","msg":"No peers with score 1. Finding peers with score 0"}
{"level":"verbose","ts":1656861243.315806,"caller":"bitcoin_reader/node_manager.go:809","msg":"Retrieved peers for score range 0 and up","peer_count":24}
{"level":"verbose","ts":1656861243.315880,"caller":"bitcoin_reader/node_manager.go:835","msg":"Peers for score 0","peer_count":24}
{"level":"verbose","ts":1656861243.316573,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [157.230.41.128]:8333","connection":"c420bf34-c739-4336-9ddd-95bdf4fb232b"}
{"level":"verbose","ts":1656861243.316853,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [139.59.67.18]:8333","connection":"9e215872-3ee1-40f3-a4e2-fa8db71dd54a"}
{"level":"verbose","ts":1656861243.317773,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [206.189.128.174]:8333","connection":"2a130f72-6601-431d-ae27-6b9b0c57656e"}
{"level":"verbose","ts":1656861243.318980,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [68.183.42.63]:8333","connection":"f94ba819-7bec-4825-aced-96d5aa3caabb"}
{"level":"verbose","ts":1656861243.319678,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [157.230.26.77]:8333","connection":"5bb52f56-b086-4847-ac71-9b3a6066ad64"}
{"level":"verbose","ts":1656861243.320388,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [167.99.219.11]:8333","connection":"50aaddd4-5dab-466c-ada2-663b824e8798"}
{"level":"verbose","ts":1656861243.320608,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [52.37.72.29]:8333","connection":"5de71b4d-97ba-4c5f-94cd-8c8999abd9da"}
{"level":"verbose","ts":1656861243.320942,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [54.243.212.219]:8333","connection":"54347b01-2857-4304-8555-e9c1c61dee34"}
{"level":"verbose","ts":1656861243.321308,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [104.248.245.82]:8333","connection":"8d975989-39ea-4f15-9cf8-0986c9190af4"}
{"level":"verbose","ts":1656861243.321613,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [159.65.152.200]:8333","connection":"7971dc85-e419-40a8-ba92-aa55b0008ba2"}
{"level":"verbose","ts":1656861243.321801,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [3.125.35.60]:8333","connection":"f965e5f0-d6fc-4795-ab5e-5f1b39275ad5"}
{"level":"verbose","ts":1656861243.322084,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [68.183.207.240]:8333","connection":"54679a8b-b0b7-483c-8e7e-ade5d0c62824"}
{"level":"verbose","ts":1656861243.322252,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [206.189.104.98]:8333","connection":"82407cda-b3a6-4e7e-adb1-8cb598cfb8e2"}
{"level":"verbose","ts":1656861243.322429,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [68.183.217.44]:8333","connection":"e2316257-0977-4655-94e7-3b22f8ebf34a"}
{"level":"verbose","ts":1656861243.322655,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [142.93.153.130]:8333","connection":"2357d5eb-9b83-4c4f-afdb-da6ffe54401b"}
{"level":"verbose","ts":1656861243.322814,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [168.119.86.4]:8333","connection":"ee5ec3b2-6ca4-4371-a93f-2a78f83a82ca"}
{"level":"verbose","ts":1656861243.322948,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [178.128.168.207]:8333","connection":"a5d3cd0d-b69a-48b3-9a4f-fe763074f394"}
{"level":"verbose","ts":1656861243.323145,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [148.251.110.36]:8333","connection":"8e8f25f4-fad0-48eb-a8d8-c0a24b003041"}
{"level":"verbose","ts":1656861243.323334,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [18.192.253.59]:8333","connection":"858802b7-4dd1-457e-8f1d-2e90b7d98b93"}
{"level":"verbose","ts":1656861243.323619,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [148.251.110.44]:8333","connection":"865893d8-36dc-4cf9-a617-67e8752922fe"}
{"level":"verbose","ts":1656861243.323841,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [167.99.191.215]:8333","connection":"8f3080a5-0c24-4171-8053-93bb93977a64"}
{"level":"verbose","ts":1656861243.324084,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [65.21.122.87]:8333","connection":"95331f8b-e04d-4e50-8a80-fba164a6d3bd"}
{"level":"verbose","ts":1656861243.324250,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [168.119.86.12]:8333","connection":"7c44702c-d0a9-46d6-9be8-563fac2c83b7"}
{"level":"verbose","ts":1656861243.324477,"caller":"bitcoin_reader/node_manager.go:907","msg":"Retrieved peers for scanning","peer_count":42}
{"level":"verbose","ts":1656861243.324554,"caller":"bitcoin_reader/node_manager.go:924","msg":"Peers for scanning","peer_count":42}
{"level":"verbose","ts":1656861243.324771,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [95.217.38.93]:8333","connection":"6700ab08-ff1a-48c7-8123-e1a294cfe122"}
{"level":"verbose","ts":1656861243.324882,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [178.128.232.188]:8333","scan_connection":"ce5410f2-757f-4cd8-84a7-a63d9d1b4558"}
{"level":"info","ts":1656861243.325401,"caller":"bitcoin_reader/node_manager.go:964","msg":"Scanning nodes","new_nodes":18,"scan_count":500}
{"level":"verbose","ts":1656861243.325631,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [95.217.93.4]:8333","scan_connection":"b8d1529d-44f5-4b53-be45-3f2106a18ff7"}
{"level":"verbose","ts":1656861243.325870,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [95.217.78.169]:8333","scan_connection":"c0ac9181-2e90-4759-ae37-b4cf24be3a78"}
{"level":"warn","ts":1656861243.326060,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [157.230.26.77]:8333: connect: dial tcp 157.230.26.77:8333: connect: connection refused","connection":"5bb52f56-b086-4847-ac71-9b3a6066ad64"}
{"level":"verbose","ts":1656861243.326259,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [52.58.59.54]:8333","scan_connection":"d13b03f4-416c-40fa-b196-aef2d5279589"}
{"level":"verbose","ts":1656861243.326659,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [18.159.24.106]:8333","scan_connection":"53309bbd-aa70-4487-8882-a5352774b06e"}
{"level":"verbose","ts":1656861243.326869,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [3.120.26.103]:8333","scan_connection":"546b84ae-7c2b-4e01-91b0-ab3e7d2af14e"}
{"level":"verbose","ts":1656861243.327037,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [206.189.81.233]:8333","scan_connection":"427890b9-a105-41d7-bee9-ad1fc92ba6b0"}
{"level":"verbose","ts":1656861243.327200,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [104.248.30.60]:8333","scan_connection":"9055047e-0e8d-4cda-a9ff-7267c5de8d67"}
{"level":"verbose","ts":1656861243.327344,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [178.128.90.188]:8333","scan_connection":"e014074f-0842-4bc5-82ed-ebbeb4a7c8d0"}
{"level":"verbose","ts":1656861243.327537,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [174.138.5.253]:8333","scan_connection":"14f63efc-c9d5-4de4-9f0d-5e8229d1a968"}
{"level":"verbose","ts":1656861243.327659,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [3.120.175.133]:8333","scan_connection":"b8c77bfc-2f2d-4971-98c2-008edfdeaa77"}
{"level":"verbose","ts":1656861243.327826,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [176.9.148.163]:8333","scan_connection":"1f4d7b89-43e8-4337-af80-808ae76e62b3"}
{"level":"verbose","ts":1656861243.327974,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [178.62.199.113]:8333","scan_connection":"f5dd5d58-1499-481b-a540-8da193f4aa07"}
{"level":"verbose","ts":1656861243.328122,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [47.244.132.56]:8333","scan_connection":"848b407a-1978-40f4-b953-62616127ff77"}
{"level":"verbose","ts":1656861243.328314,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [178.62.204.112]:8333","scan_connection":"b2718556-4c7d-4a3e-8904-35603f38c1c4"}
{"level":"verbose","ts":1656861243.328476,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [167.99.92.186]:8333","scan_connection":"5ae12374-540c-498f-9b9d-077809608731"}
{"level":"verbose","ts":1656861243.328962,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [120.79.201.111]:8333","scan_connection":"5420c9a5-8602-40ba-b8ec-03bf4dc96d56"}
{"level":"verbose","ts":1656861243.329213,"caller":"bitcoin_reader/bitcoin_node.go:365","msg":"Connecting to [18.159.232.188]:8333","scan_connection":"830c5da9-ad1d-40ff-832b-d31b24c70f36"}
{"level":"verbose","ts":1656861243.329538,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 104.248.245.82:8333","connection":"8d975989-39ea-4f15-9cf8-0986c9190af4"}
{"level":"warn","ts":1656861243.329764,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [68.183.217.44]:8333: connect: dial tcp 68.183.217.44:8333: connect: connection refused","connection":"e2316257-0977-4655-94e7-3b22f8ebf34a"}
{"level":"verbose","ts":1656861243.329856,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 3.125.35.60:8333","connection":"f965e5f0-d6fc-4795-ab5e-5f1b39275ad5"}
{"level":"verbose","ts":1656861243.330198,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 18.192.253.59:8333","connection":"858802b7-4dd1-457e-8f1d-2e90b7d98b93"}
{"level":"info","ts":1656861243.330656,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"8d975989-39ea-4f15-9cf8-0986c9190af4"}
{"level":"verbose","ts":1656861243.333143,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 52.58.59.54:8333","scan_connection":"d13b03f4-416c-40fa-b196-aef2d5279589"}
{"level":"warn","ts":1656861243.333608,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [168.119.86.12]:8333: connect: dial tcp 168.119.86.12:8333: connect: no route to host","connection":"7c44702c-d0a9-46d6-9be8-563fac2c83b7"}
{"level":"verbose","ts":1656861243.333696,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 18.159.24.106:8333","scan_connection":"53309bbd-aa70-4487-8882-a5352774b06e"}
{"level":"verbose","ts":1656861243.333828,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 3.120.26.103:8333","scan_connection":"546b84ae-7c2b-4e01-91b0-ab3e7d2af14e"}
{"level":"verbose","ts":1656861243.334488,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 3.120.175.133:8333","scan_connection":"b8c77bfc-2f2d-4971-98c2-008edfdeaa77"}
{"level":"info","ts":1656861243.335670,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"f965e5f0-d6fc-4795-ab5e-5f1b39275ad5"}
{"level":"info","ts":1656861243.336847,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"858802b7-4dd1-457e-8f1d-2e90b7d98b93"}
{"level":"warn","ts":1656861243.337321,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [167.99.219.11]:8333: connect: dial tcp 167.99.219.11:8333: connect: connection refused","connection":"50aaddd4-5dab-466c-ada2-663b824e8798"}
{"level":"verbose","ts":1656861243.337742,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 168.119.86.4:8333","connection":"ee5ec3b2-6ca4-4371-a93f-2a78f83a82ca"}
{"level":"verbose","ts":1656861243.339726,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 176.9.148.163:8333","scan_connection":"1f4d7b89-43e8-4337-af80-808ae76e62b3"}
{"level":"verbose","ts":1656861243.339817,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 148.251.110.44:8333","connection":"865893d8-36dc-4cf9-a617-67e8752922fe"}
{"level":"verbose","ts":1656861243.340042,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 18.159.232.188:8333","scan_connection":"830c5da9-ad1d-40ff-832b-d31b24c70f36"}
{"level":"info","ts":1656861243.340187,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"d13b03f4-416c-40fa-b196-aef2d5279589"}
{"level":"verbose","ts":1656861243.340458,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 206.189.104.98:8333","connection":"82407cda-b3a6-4e7e-adb1-8cb598cfb8e2"}
{"level":"verbose","ts":1656861243.340619,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 148.251.110.36:8333","connection":"8e8f25f4-fad0-48eb-a8d8-c0a24b003041"}
{"level":"info","ts":1656861243.340747,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"546b84ae-7c2b-4e01-91b0-ab3e7d2af14e"}
{"level":"info","ts":1656861243.341142,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"53309bbd-aa70-4487-8882-a5352774b06e"}
{"level":"info","ts":1656861243.341784,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"b8c77bfc-2f2d-4971-98c2-008edfdeaa77"}
{"level":"verbose","ts":1656861243.344328,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 68.183.42.63:8333","connection":"f94ba819-7bec-4825-aced-96d5aa3caabb"}
{"level":"info","ts":1656861243.345065,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"830c5da9-ad1d-40ff-832b-d31b24c70f36"}
{"level":"verbose","ts":1656861243.350372,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 174.138.5.253:8333","scan_connection":"14f63efc-c9d5-4de4-9f0d-5e8229d1a968"}
{"level":"info","ts":1656861243.351723,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"1f4d7b89-43e8-4337-af80-808ae76e62b3"}
{"level":"verbose","ts":1656861243.352207,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 178.62.204.112:8333","scan_connection":"b2718556-4c7d-4a3e-8904-35603f38c1c4"}
{"level":"verbose","ts":1656861243.353920,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 167.99.92.186:8333","scan_connection":"5ae12374-540c-498f-9b9d-077809608731"}
{"level":"verbose","ts":1656861243.354252,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 65.21.122.87:8333","connection":"95331f8b-e04d-4e50-8a80-fba164a6d3bd"}
{"level":"info","ts":1656861243.354486,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"865893d8-36dc-4cf9-a617-67e8752922fe"}
{"level":"info","ts":1656861243.354680,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"8e8f25f4-fad0-48eb-a8d8-c0a24b003041"}
{"level":"info","ts":1656861243.354879,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"ee5ec3b2-6ca4-4371-a93f-2a78f83a82ca"}
{"level":"verbose","ts":1656861243.356207,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 95.217.78.169:8333","scan_connection":"c0ac9181-2e90-4759-ae37-b4cf24be3a78"}
{"level":"verbose","ts":1656861243.358859,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 95.217.38.93:8333","connection":"6700ab08-ff1a-48c7-8123-e1a294cfe122"}
{"level":"info","ts":1656861243.359178,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"82407cda-b3a6-4e7e-adb1-8cb598cfb8e2"}
{"level":"info","ts":1656861243.368848,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"f94ba819-7bec-4825-aced-96d5aa3caabb"}
{"level":"info","ts":1656861243.373736,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"14f63efc-c9d5-4de4-9f0d-5e8229d1a968"}
{"level":"info","ts":1656861243.376876,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"b2718556-4c7d-4a3e-8904-35603f38c1c4"}
{"level":"info","ts":1656861243.377324,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"5ae12374-540c-498f-9b9d-077809608731"}
{"level":"info","ts":1656861243.383431,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"95331f8b-e04d-4e50-8a80-fba164a6d3bd"}
{"level":"info","ts":1656861243.388497,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: read tcp 207.180.192.123:53478->95.217.78.169:8333: read: connection reset by peer","scan_connection":"c0ac9181-2e90-4759-ae37-b4cf24be3a78"}
{"level":"info","ts":1656861243.392656,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: read tcp 207.180.192.123:59892->95.217.38.93:8333: read: connection reset by peer","connection":"6700ab08-ff1a-48c7-8123-e1a294cfe122"}
{"level":"warn","ts":1656861243.435559,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [68.183.207.240]:8333: connect: dial tcp 68.183.207.240:8333: connect: connection refused","connection":"54679a8b-b0b7-483c-8e7e-ade5d0c62824"}
{"level":"warn","ts":1656861243.437533,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [167.99.191.215]:8333: connect: dial tcp 167.99.191.215:8333: connect: connection refused","connection":"8f3080a5-0c24-4171-8053-93bb93977a64"}
{"level":"verbose","ts":1656861243.437753,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 178.128.232.188:8333","scan_connection":"ce5410f2-757f-4cd8-84a7-a63d9d1b4558"}
{"level":"verbose","ts":1656861243.495265,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 52.37.72.29:8333","connection":"5de71b4d-97ba-4c5f-94cd-8c8999abd9da"}
{"level":"info","ts":1656861243.558945,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"ce5410f2-757f-4cd8-84a7-a63d9d1b4558"}
{"level":"warn","ts":1656861243.561181,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [157.230.41.128]:8333: connect: dial tcp 157.230.41.128:8333: connect: connection refused","connection":"c420bf34-c739-4336-9ddd-95bdf4fb232b"}
{"level":"verbose","ts":1656861243.591431,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 139.59.67.18:8333","connection":"9e215872-3ee1-40f3-a4e2-fa8db71dd54a"}
{"level":"warn","ts":1656861243.591790,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [206.189.128.174]:8333: connect: dial tcp 206.189.128.174:8333: connect: connection refused","connection":"2a130f72-6601-431d-ae27-6b9b0c57656e"}
{"level":"verbose","ts":1656861243.591894,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 206.189.81.233:8333","scan_connection":"427890b9-a105-41d7-bee9-ad1fc92ba6b0"}
{"level":"verbose","ts":1656861243.593974,"caller":"bitcoin_reader/bitcoin_node.go:648","msg":"Connected to 159.65.152.200:8333","connection":"7971dc85-e419-40a8-ba92-aa55b0008ba2"}
{"level":"warn","ts":1656861243.643975,"caller":"bitcoin_reader/node_manager.go:949","msg":"Finished: Scan Node: [47.244.132.56]:8333: connect: dial tcp 47.244.132.56:8333: connect: connection refused","scan_connection":"848b407a-1978-40f4-b953-62616127ff77"}
{"level":"info","ts":1656861243.678952,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"5de71b4d-97ba-4c5f-94cd-8c8999abd9da"}
{"level":"info","ts":1656861243.850130,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","scan_connection":"427890b9-a105-41d7-bee9-ad1fc92ba6b0"}
{"level":"info","ts":1656861243.866446,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: EOF","connection":"9e215872-3ee1-40f3-a4e2-fa8db71dd54a"}
{"level":"info","ts":1656861243.872757,"caller":"bitcoin_reader/messages.go:76","msg":"Connection closed remotely : header: network: read tcp 207.180.192.123:45500->159.65.152.200:8333: read: connection reset by peer","connection":"7971dc85-e419-40a8-ba92-aa55b0008ba2"}
{"level":"warn","ts":1656861248.321461,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [54.243.212.219]:8333: connect: dial tcp 54.243.212.219:8333: i/o timeout","connection":"54347b01-2857-4304-8555-e9c1c61dee34"}
{"level":"warn","ts":1656861248.323006,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [142.93.153.130]:8333: connect: dial tcp 142.93.153.130:8333: i/o timeout","connection":"2357d5eb-9b83-4c4f-afdb-da6ffe54401b"}
{"level":"warn","ts":1656861248.323284,"caller":"bitcoin_reader/node_manager.go:873","msg":"Finished: Node: [178.128.168.207]:8333: connect: dial tcp 178.128.168.207:8333: i/o timeout","connection":"a5d3cd0d-b69a-48b3-9a4f-fe763074f394"}
panic: runtime error: index out of range [0] with length 0

goroutine 39 [running]:
github.com/tokenized/bitcoin_reader.(*NodeManager).nextNode(0xc0004af540, 0xf4b6c0, 0xc0001cf920, 0x0, 0x1)
        /root/bitcoin_reader/node_manager.go:222 +0xf68
github.com/tokenized/bitcoin_reader.(*NodeManager).RequestTxs(0xc0004af540, 0xf4b6c0, 0xc0001cf920, 0x0, 0x0)
        /root/bitcoin_reader/node_manager.go:161 +0x19f
github.com/tokenized/pkg/threads.(*Thread).runPeriodic(0xc0004e0200, 0xf4b6c0, 0xc0001cf5c0, 0xc00047c120, 0x22)
        /root/go/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:216 +0xf5
github.com/tokenized/pkg/threads.(*Thread).Start.func1(0xf4b6c0, 0xc0001cf5c0, 0xc00047c120, 0x22, 0xbf3cc5, 0xb, 0xc0004e0200)
        /root/go/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:179 +0x5da
created by github.com/tokenized/pkg/threads.(*Thread).Start
        /root/go/pkg/mod/github.com/tokenized/pkg@v0.4.1-0.20220524020344-6bbdcf489d31/threads/threads.go:169 +0xe4
exit status 2
```
